version: "3.8"

# gpuci has 2 AMD EPYC 7402 CPUs, 48 threads in total, with 504GB of RAM

services:
  buildkite:
    hostname: gpuci.16
    build:
      context: ../../image/
      args:
        base: nvidia/cuda:12.1.0-devel-ubuntu20.04
    runtime: nvidia
    environment:
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      NVIDIA_VISIBLE_DEVICES: "GPU-ec68e28e-d7c6-21eb-8223-88cb012eae5c"
      JULIA_CPU_THREADS: 2
    pid: "host" #  NVIDIA/gpu-monitoring-tools#63
    env_file: ../token.env
    command:
      - start
      - --disconnect-after-job
      - --hooks-path=/hooks
      - --tags=queue=juliagpu,cuda,cap=sm_75,gpu=rtx5000,cap=recent
      - --name=gpuci.16
      - --priority=4
    volumes:
      - /home/buildkite/gpuci.16:/root
