version: "3.8"

# gpuci has 2 AMD EPYC 7402 CPUs, 48 threads in total, with 504GB of RAM

services:
  buildkite:
    hostname: gpuci.16
    build:
      context: ../../image/
      args:
        base: nvidia/cuda:11.6.1-cudnn8-devel-ubuntu20.04
    runtime: nvidia
    environment:
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      NVIDIA_VISIBLE_DEVICES: "GPU-ec68e28e-d7c6-21eb-8223-88cb012eae5c"
      JULIA_NUM_THREADS: 2
    pid: "host" #  NVIDIA/gpu-monitoring-tools#63
    env_file: ../token.env
    command:
      - start
      - --disconnect-after-job
      - --hooks-path=/hooks
      - --tags=queue=juliagpu,cuda=9.0,cuda=9.2,cuda=10.0,cuda=10.1,cuda=10.2,cuda=11.0,cuda=11.1,cuda=11.2,cuda=11.3,cuda=11.4,cap=sm_75,cap=recent
      - --name=gpuci.16
      - --priority=4
    volumes:
      - /home/buildkite/gpuci.16:/root
