version: "3.8"

# gpuci2 has an AMD FX-8350, 8 threads in total,
# with 16GB of RAM, and 8GB of VRAM

services:
  buildkite:
    hostname: gpuci2.julia.csail.mit.edu
    build:
      context: ../../image/
      args:
        base: nvidia/cuda:11.2.1-cudnn8-devel-ubuntu20.04
    runtime: nvidia
    environment:
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      JULIA_NUM_THREADS: 3
    pid: "host" #  NVIDIA/gpu-monitoring-tools#63
    env_file: ../token.env
    command:
      - start
      - --disconnect-after-job
      - --hooks-path=/hooks
      - --tags=queue=benchmark,cuda=9.0,cuda=9.2,cuda=10.0,cuda=10.1,cuda=10.2,cuda=11.0,cuda=11.1,cuda=11.2,cap=sm_75,cap=recent
      - --name=rtx2070.gpuci2.julia.csail.mit.edu
      - --priority=3
    volumes:
      - /home/buildkite/rtx2070:/root
