version: "3.8"

# cyclops has 2 6-core Intel Xeon E5-2603 v4, 12 threads in total,
# with 378GB of RAM and 16-32GB of VRAM per V100
#
# since this system is so underpowered CPU-wise, we make it a multigpu runner

services:
  buildkite:
    hostname: cyclops.juliacomputing.io
    build:
      context: ../../image/
      args:
        base: nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04
    runtime: nvidia
    environment:
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      NVIDIA_VISIBLE_DEVICES: "GPU-f735dd37-372b-a4c1-f643-cca0b729e13a"
      JULIA_NUM_THREADS: 3
    pid: "host" #  NVIDIA/gpu-monitoring-tools#63
    env_file: ../token.env
    command:
      - start
      - --disconnect-after-job
      - --hooks-path=/hooks
      - --tags=queue=juliagpu,cuda=9.0,cuda=9.2,cuda=10.0,cuda=10.1,cuda=10.2,cuda=11.0,cuda=11.1,cuda=11.2,cap=sm_75,cap=recent
      - --name=2.cyclops.juliacomputing.io
      - --priority=1
    volumes:
      - /home/buildkite/2:/root
