version: "3.8"

# gpuci has 2 AMD EPYC 7402 CPUs, 48 threads in total, with 504GB of RAM

services:
  buildkite:
    hostname: gpuci.12
    build:
      context: ../../image/
      args:
        base: nvidia/cuda:12.1.0-devel-ubuntu20.04
    runtime: nvidia
    environment:
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      NVIDIA_VISIBLE_DEVICES: "MIG-9840604c-ee1c-586c-83d1-f0781e1aad49"
      JULIA_CPU_THREADS: 2
    pid: "host" #  NVIDIA/gpu-monitoring-tools#63
    env_file: ../token.env
    command:
      - start
      - --disconnect-after-job
      - --hooks-path=/hooks
      - --tags=queue=juliagpu,cuda,cap=sm_80,gpu=a100,cap=recent
      - --name=gpuci.12
      - --priority=4
    volumes:
      - /home/buildkite/gpuci.12:/root
