version: "3.8"

# gpuci1 has an i7-9700K, 8 threads in total,
# with 16GB of RAM, and 8GB of VRAM

services:
  buildkite:
    hostname: gpuci1
    build:
      context: ../../image/
      args:
        base: nvidia/cuda:12.1.0-devel-ubuntu20.04
    runtime: nvidia
    environment:
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      JULIA_CPU_THREADS: 2
    pid: "host" #  NVIDIA/gpu-monitoring-tools#63
    devices:
      - "/dev/dri:/dev/dri"
    env_file: ../token.env
    command:
      - start
      - --disconnect-after-job
      - --hooks-path=/hooks
      - --tags=queue=benchmark,cuda,cap=sm_75,cap=recent,gpu=rtx2070,intel=gen9
      - --name=gpuci1
      - --priority=3
    volumes:
      - /home/buildkite:/root
