# gpuci has 2 AMD EPYC 7402 CPUs, 48 threads in total, with 504GB of RAM

services:
  buildkite:
    hostname: gpuci.11
    build:
      context: ../../image/
      args:
        base: nvidia/cuda:12.6.2-devel-ubuntu22.04
    runtime: nvidia
    environment:
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      NVIDIA_VISIBLE_DEVICES: "MIG-b147d00d-faab-56ef-bc9c-219152732827"
      JULIA_CPU_THREADS: 2
    pid: "host" #  NVIDIA/gpu-monitoring-tools#63
    env_file: ../token.env
    command:
      - start
      - --disconnect-after-job
      - --hooks-path=/hooks
      - --tags=queue=juliagpu,cuda,cap=sm_80,gpu=a100,cap=recent
      - --name=gpuci.11
      - --priority=4
    volumes:
      - /home/buildkite/gpuci.11:/root
