version: "3.8"

# hydor has 2 quad core Intel Xeon E5-2637, 16 threads in total,
# with 64GB of RAM and 11GB of VRAM

services:
  buildkite:
    hostname: hydor.elis.ugent.be
    build:
      context: ../../image/
      args:
        base: nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04
    runtime: nvidia
    environment:
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      NVIDIA_VISIBLE_DEVICES: "GPU-fa79b18d-3e09-142a-2493-bb83b07b0bdf"
      JULIA_NUM_THREADS: 4
    pid: "host" #  NVIDIA/gpu-monitoring-tools#63
    env_file: ../token.env
    command:
      - start
      - --disconnect-after-job
      - --hooks-path=/hooks
      - --tags=queue=juliagpu,cuda=10.0,cuda=10.1,cuda=10.2,cuda=11.0,cuda=9.0,cuda=9.2,cap=sm_75,cap=recent
      - --name=rtx2080.hydor.elis.ugent.be
      - --priority=2
    volumes:
      - /storage/buildkite/rtx2080:/root
