# an Intel NUC 11 (NUC11PAHi7) containing a i7-1165G7 (8 threads) with 32GiB RAM

services:
  buildkite:
    hostname: sagittarius.maleadt.net
    build:
      context: ../../image/
      args:
        base: gcc
    devices:
      - "/dev/dri:/dev/dri"
    environment:
      JULIA_CPU_THREADS: 4
    env_file: ../token.env
    command:
      - start
      - --disconnect-after-job
      - --hooks-path=/hooks
      - --tags=queue=juliagpu,intel=gen12
      - --name=sagittarius.maleadt.net
    volumes:
      - /home/buildkite:/root
