version: "3.8"

# helios has a 12-core (24-thread) Ryzen Threadripper 1920X,
# with 32GB of RAM
# two GPUs are available:
# - Radeon Vega 56 (8GB) (MSI)
# - Radeon Vega 56 (8GB) (Sapphire)
# only one GPU is available per agent

services:
  buildkite:
    hostname: helios.jpsamaroo.me
    build:
      context: ../../image/
      args:
        base: jps/rocm-ci
    environment:
      JULIA_NUM_THREADS: 4
    devices:
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
      - "/dev/kfd:/dev/kfd"
    security_opt:
      - seccomp:unconfined
    privileged: true
    env_file: ../../token.env
    command:
      - start
      - --disconnect-after-job
      - --hooks-path=/hooks
      - --tags=queue=juliagpu,rocm
      - --name=1.helios.jpsamaroo.me
      - --priority=1
    volumes:
      - /home/buildkite/1:/root
