#!/bin/bash
set -euo pipefail


# only decrypt secrets if this is a trusted environment (i.e., not a third-party PR)
if [[ "${BUILDKITE_PULL_REQUEST}" == "false" ||
      "${BUILDKITE_PULL_REQUEST_REPO}" == "${BUILDKITE_REPO}" ]]; then
    echo "--- :key: Decrypting secrets"

    for value_var in $(set | awk -F "=" '{print $1}' | grep "SECRET_"); do
        name=${value_var:7}
        echo "Found secret for $name"
        secret=${!value_var}

        encrypted_key=$(echo "$secret" | cut -d ';' -f 1)
        keyfile=$(mktemp)
        echo "$encrypted_key" |
            openssl base64 -d -A |
            openssl rsautl -decrypt -inkey /secrets.private.key -out "$keyfile"

        encrypted_value=$(echo "$secret" | cut -d ';' -f 2)
        value=$(echo "$encrypted_value" |
                openssl base64 -d -A |
                openssl enc -d -aes-256-cbc -pbkdf2 -iter 100000 -pass "file:$keyfile")

        export "$name"="$value"
        shred -u "$keyfile"
    done
else
    echo "--- :key: Skipping decryption of secrets"
fi

rm /secrets.private.key
