version: "3.8"

# gpuci3 has an i7-9700K, 8 threads in total, with an integrated UHD Graphics 630

services:
  buildkite:
    hostname: gpuci3
    build:
      context: ../../image/
      args:
        base: intelopencl/intel-opencl:ubuntu-20.04-ppa
    devices:
      - "/dev/dri:/dev/dri"
    environment:
      JULIA_NUM_THREADS: 1
    env_file: ../token.env
    command:
      - start
      - --disconnect-after-job
      - --hooks-path=/hooks
      - --tags=queue=juliagpu,intel=gen9
      - --name=gpuci3
    volumes:
      - /home/buildkite:/root
