#!/usr/bin/env bash
set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

read -p 'Variable name: ' var

read -sp 'Secret value: ' val
echo "$val" | sed 's/./*/g'

# generate a random symmetric key for this repo
keyfile=$(mktemp)
openssl rand -base64 128 > $keyfile

# encrypt the key
encrypted_key=$(openssl rsautl -encrypt -pubin -inkey $DIR/../image/secrets.public.key -in $keyfile |
                openssl base64 -A |
                tr -d '\n')

# encrypt the value
encrypted=$(echo $val |
            openssl enc -aes-256-cbc -salt -pbkdf2 -iter 100000 -pass file:$keyfile |
            openssl base64 -A |
            tr -d '\n')

cat <<EOD

Add the following snippet to your pipeline.yml:

env:
  SECRET_$var: "$encrypted_key;$encrypted"
EOD

shred -u $keyfile
