version: "3.8"

# ripper has a AMD Ryzen Threadripper 2990WX, 64 threads in total,
# with 64GB of RAM, and 6GB of VRAM

services:
  buildkite:
    hostname: ripper.elis.ugent.be
    build:
      context: ../../image/
      args:
        base: nvidia/cuda:11.0.3-cudnn8-devel-ubuntu20.04
    runtime: nvidia
    environment:
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      NVIDIA_VISIBLE_DEVICES: "GPU-a6bf77e4-bd78-16b3-6162-98b5ee866a6e"
      JULIA_NUM_THREADS: 2
    pid: "host" #  NVIDIA/gpu-monitoring-tools#63
    env_file: ../token.env
    command:
      - start
      - --disconnect-after-job
      - --hooks-path=/hooks
      - --tags=queue=juliagpu,cuda=10.0,cuda=10.1,cuda=10.2,cuda=11.0,cuda=9.0,cuda=9.2,cap=sm_35
      - --name=titan.ripper.elis.ugent.be
      - --priority=3
    volumes:
      - /storage/buildkite/titan:/root
